import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../api/client';
import { useAuth } from '../AuthContext';

export default function PrintInvoice() {
  const { id } = useParams();
  const { user } = useAuth();
  const isPatient = user?.role === 'patient';

  const [data, setData] = useState(null);
  const [patientInfo, setPatientInfo] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const result = isPatient ? await api.portal.getInvoice(id) : await api.billing.getInvoice(id);
        setData(result);
        // The patient-scoped endpoint doesn't join patient_name/patient_code
        // onto the invoice (it doesn't need to — the patient already knows
        // who they are) — fetch it separately for the printed header.
        if (isPatient && !result.invoice.patient_name) {
          const { patient } = await api.portal.me();
          setPatientInfo(patient);
        }
      } catch (err) {
        setError(err.message);
      }
    }
    load();
  }, [id, isPatient]);

  if (error) return <div className="print-page"><div className="error-banner">{error}</div></div>;
  if (!data) return <div className="print-page">Loading…</div>;

  const { invoice, items, payments } = data;
  const patientName = invoice.patient_name || patientInfo?.full_name || '—';
  const patientCode = invoice.patient_code || patientInfo?.patient_code || '—';
  const balance = Number(invoice.total_amount) - Number(invoice.amount_paid);

  return (
    <div className="print-page">
      <div className="print-actions">
        <button className="btn btn-primary" onClick={() => window.print()}>Print / Save as PDF</button>
      </div>

      <div className="print-header">
        <div>
          <div className="print-brand">Wardline<span style={{ color: 'var(--amber)' }}>.</span></div>
          <div style={{ fontSize: '0.8rem', color: 'var(--muted)' }}>Local Hospital Invoice</div>
        </div>
        <div className="print-meta">
          <div>Invoice #{invoice.id}</div>
          <div>{new Date(invoice.created_at).toLocaleDateString()}</div>
          <div style={{ textTransform: 'capitalize', fontWeight: 700, marginTop: 4 }}>{invoice.status.replace('_', ' ')}</div>
        </div>
      </div>

      <div className="print-section">
        <h3>Patient</h3>
        <div>{patientName}</div>
        <div className="mono" style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>{patientCode}</div>
      </div>

      <div className="print-section">
        <h3>Charges</h3>
        <table className="print-table">
          <thead>
            <tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Line total</th></tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
                <td>{item.description}</td>
                <td>{item.quantity}</td>
                <td className="mono">{Number(item.unit_price).toFixed(2)}</td>
                <td className="mono">{Number(item.line_total).toFixed(2)}</td>
              </tr>
            ))}
            <tr className="print-total-row">
              <td colSpan={3}>Total</td>
              <td className="mono">{Number(invoice.total_amount).toFixed(2)}</td>
            </tr>
            <tr>
              <td colSpan={3}>Paid</td>
              <td className="mono">{Number(invoice.amount_paid).toFixed(2)}</td>
            </tr>
            <tr>
              <td colSpan={3}><strong>Balance due</strong></td>
              <td className="mono"><strong>{balance.toFixed(2)}</strong></td>
            </tr>
          </tbody>
        </table>
      </div>

      {payments.length > 0 && (
        <div className="print-section">
          <h3>Payments received</h3>
          <table className="print-table">
            <thead><tr><th>Date</th><th>Method</th><th>Amount</th></tr></thead>
            <tbody>
              {payments.map((p) => (
                <tr key={p.id}>
                  <td>{new Date(p.paid_at).toLocaleDateString()}</td>
                  <td style={{ textTransform: 'capitalize' }}>{(p.method || '').replace('_', ' ')}</td>
                  <td className="mono">{Number(p.amount).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginTop: 30 }}>
        Generated by Wardline on {new Date().toLocaleString()}.
      </p>
    </div>
  );
}
