import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../api/client';
import { useAuth } from '../AuthContext';

export default function PrintPrescription() {
  const { id } = useParams();
  const { user } = useAuth();
  const isPatient = user?.role === 'patient';

  const [data, setData] = useState(null);
  const [patientInfo, setPatientInfo] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const result = isPatient ? await api.portal.getPrescription(id) : await api.pharmacy.getPrescription(id);
        setData(result);
        if (isPatient && !result.prescription.patient_name) {
          const { patient } = await api.portal.me();
          setPatientInfo(patient);
        }
      } catch (err) {
        setError(err.message);
      }
    }
    load();
  }, [id, isPatient]);

  if (error) return <div className="print-page"><div className="error-banner">{error}</div></div>;
  if (!data) return <div className="print-page">Loading…</div>;

  const { prescription, items } = data;
  const patientName = prescription.patient_name || patientInfo?.full_name || '—';
  const patientCode = prescription.patient_code || patientInfo?.patient_code || '—';

  return (
    <div className="print-page">
      <div className="print-actions">
        <button className="btn btn-primary" onClick={() => window.print()}>Print / Save as PDF</button>
      </div>

      <div className="print-header">
        <div>
          <div className="print-brand">Wardline<span style={{ color: 'var(--amber)' }}>.</span></div>
          <div style={{ fontSize: '0.8rem', color: 'var(--muted)' }}>Prescription</div>
        </div>
        <div className="print-meta">
          <div>Rx #{prescription.id}</div>
          <div>{new Date(prescription.created_at).toLocaleDateString()}</div>
        </div>
      </div>

      <div className="print-section">
        <h3>Patient</h3>
        <div>{patientName}</div>
        <div className="mono" style={{ color: 'var(--muted)', fontSize: '0.85rem' }}>{patientCode}</div>
      </div>

      <div className="print-section">
        <h3>Prescribed by</h3>
        <div>Dr. {prescription.prescribed_by_name}</div>
      </div>

      <div className="print-section">
        <h3>Medication</h3>
        <table className="print-table">
          <thead>
            <tr><th>Medicine</th><th>Dosage</th><th>Frequency</th><th>Duration</th></tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
                <td>{item.medicine_name}</td>
                <td>{item.dosage || '—'}</td>
                <td>{item.frequency || '—'}</td>
                <td>{item.duration_days ? `${item.duration_days} days` : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginTop: 30 }}>
        Generated by Wardline on {new Date().toLocaleString()}. Take medication exactly as directed
        by your prescribing doctor.
      </p>
    </div>
  );
}
